# Generated by Django 5.2.12 on 2026-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Pagamento MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Preferência MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo do Frete'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('retirada', 'Retirada na Loja'), ('frete_fixo', 'Frete Fixo')], default='retirada', max_length=20, verbose_name='Método de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('aguardando_arte', 'Aguardando Arte'), ('arte_recebida', 'Arte Recebida'), ('em_producao', 'Em Produção'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_pagamento', max_length=30),
        ),
    ]
