# Generated by Django 5.2.12 on 2026-03-10 19:39

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_mp_payment_id_order_mp_preference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='art_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.orders.models.order_item_art_upload_path, verbose_name='Arquivo da Arte'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='art_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status da Arte'),
        ),
    ]
