# Generated by Django 5.2.12 on 2026-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_art_file_orderitem_art_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Retirada na Loja', max_length=150, verbose_name='Método de Entrega'),
        ),
    ]
