# Generated by Django 5.2.12 on 2026-03-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelDeProducao',
            fields=[
            ],
            options={
                'verbose_name': '🗂️ Kanban de Produção',
                'verbose_name_plural': '🗂️ Kanban de Produção',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
