# Generated by Django 5.2.12 on 2026-03-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paineldeproducao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paineldeproducao',
            options={'verbose_name': 'Kanban de Producao', 'verbose_name_plural': 'Kanban de Producao'},
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
    ]
