# Generated by Django 5.2.12 on 2026-03-18 20:02 (edited manually to handle existing rows)

import uuid
from django.db import migrations, models


def populate_art_approval_tokens(apps, schema_editor):
    """Gera um UUID único para cada OrderItem existente."""
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.all():
        item.art_approval_token = uuid.uuid4()
        item.save(update_fields=['art_approval_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_paineldeproducao_options_order_reviewed'),
    ]

    operations = [
        # 1. Proxy model do Dashboard
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),

        # 2. Adiciona campo SEM unique constraint ainda
        migrations.AddField(
            model_name='orderitem',
            name='art_approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
            preserve_default=False,
        ),

        # 3. Popula todos os rows existentes com UUIDs únicos
        migrations.RunPython(populate_art_approval_tokens, migrations.RunPython.noop),

        # 4. Agora aplica o unique constraint com segurança
        migrations.AlterField(
            model_name='orderitem',
            name='art_approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # 5. Campo de motivo de rejeição
        migrations.AddField(
            model_name='orderitem',
            name='art_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de Rejeicao'),
        ),
    ]
