# Generated by Django 5.2.12 on 2026-03-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dashboardproxy_orderitem_art_approval_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_origem', models.CharField(default='70000-000', max_length=9, verbose_name='CEP de Origem (Sua loja)')),
                ('dias_adicionais', models.PositiveIntegerField(default=1, help_text='Adicionado ao prazo da transportadora', verbose_name='Dias Adicionais (Prazo Extra)')),
                ('melhor_envio_token', models.TextField(blank=True, help_text='Se preenchido, ativa o cálculo real via API.', verbose_name='Token Melhor Envio')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Modo Teste (Sandbox Melhor Envio)')),
                ('enable_local_delivery', models.BooleanField(default=True, verbose_name='Ativar Frete Motoboy/Local')),
                ('local_city', models.CharField(default='Brasília', max_length=100, verbose_name='Cidade Local')),
                ('local_price', models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='Preço Base (Local)')),
            ],
            options={
                'verbose_name': 'Configuração de Frete',
                'verbose_name_plural': 'Configurações de Frete',
            },
        ),
    ]
