# Generated by Django 5.2.12 on 2026-03-09 17:49

import apps.artwork.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.artwork.models.artwork_upload_path, verbose_name='Arquivo de Arte')),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Arte do Cliente',
                'verbose_name_plural': 'Artes dos Clientes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
