# Generated by Django 5.2.12 on 2026-03-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NGD Site', max_length=255, verbose_name='Nome do Site')),
                ('meta_title_default', models.CharField(default='NGD Site - Gráfica', max_length=255, verbose_name='Título Padrão (Meta Title)')),
                ('meta_description_default', models.TextField(default='A revolução gráfica em materiais para PDV.', verbose_name='Descrição Padrão (Meta Description)')),
                ('meta_keywords_default', models.TextField(blank=True, verbose_name='Palavras-chave (Meta Keywords)')),
                ('og_image_default', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Imagem Open Graph (Padrão)')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='ID Facebook Pixel')),
            ],
            options={
                'verbose_name': 'Configuração de SEO',
                'verbose_name_plural': 'Configurações de SEO',
            },
        ),
    ]
