# Generated by Django 6.0.3 on 2026-03-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Exemplo: Categoria para placas no poliondas', verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Exemplo: Placa de sinalização no poliondas', verbose_name='Descrição Curta')),
                ('description', models.TextField(blank=True, help_text='Exemplo: Descrição detalhada do material no poliondas', verbose_name='Descrição')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='products/featured/', verbose_name='Imagem de Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('size_label', models.CharField(help_text='Ex: 40x120', max_length=100, verbose_name='Tamanho (Rótulo)')),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Largura (cm)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Altura (cm)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='products/templates/', verbose_name='Gabarito')),
                ('manual_file', models.FileField(blank=True, null=True, upload_to='products/manuals/', verbose_name='Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variante de Produto',
                'verbose_name_plural': 'Variantes de Produto',
            },
        ),
    ]
