# Generated by Django 5.2.12 on 2026-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Comprimento/Prof (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='Peso (kg)'),
        ),
    ]
