# Generated by Django 5.2.12 on 2026-05-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_length_cm_productvariant_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuTotensCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Totem Triangular', max_length=80, verbose_name='Título do card')),
                ('image', models.ImageField(blank=True, help_text='Recomendado: PNG transparente, ~600x800px', null=True, upload_to='megamenu/totens/', verbose_name='Imagem do card')),
                ('custom_url', models.CharField(blank=True, help_text='Opcional. Se preenchido, sobrescreve o link do produto.', max_length=255, verbose_name='URL customizada')),
                ('badge', models.CharField(blank=True, choices=[('', '— sem badge —'), ('novo', 'Novo'), ('mais_vendido', 'Mais vendido'), ('em_breve', 'Em breve'), ('destaque', 'Destaque')], default='', max_length=20, verbose_name='Selo / Badge')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(blank=True, help_text='Se preenchido, o card linka para a página do produto e usa o preço da 1ª variante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megamenu_cards', to='catalog.product', verbose_name='Produto vinculado')),
            ],
            options={
                'verbose_name': 'Card Megamenu Totens PDV',
                'verbose_name_plural': 'Megamenu Totens PDV',
                'ordering': ['order', 'id'],
            },
        ),
    ]
